# services:
#   - type: web
#     name: hoks
#     runtime: node
#     plan: free
#     buildCommand: npm install && npm run build
#     startCommand: npm start
#     envVars:
#       - key: NODE_ENV
#         value: production
#       - key: DATABASE_URL
#         fromDatabase:
#           name: hoks-db
#           property: connectionString

# databases:
#   - name: hoks-db
#     plan: free
#     databaseName: hoks
#     user: hoks_user

services:
  - type: web
    name: hoks
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: hoks-db
          property: connectionString

databases:
  - name: hoks-db
    plan: free
    databaseName: hoks
    user: hoks_user
